#!/bin/bash

# Script to help add test target to Xcode project
echo "================================"
echo "Test Target Setup Instructions"
echo "================================"
echo ""
echo "The test files have been created. To complete the setup:"
echo ""
echo "1. Open your project in Xcode:"
echo "   open rmProApp.xcodeproj"
echo ""
echo "2. In Xcode, go to File → New → Target"
echo ""
echo "3. Select 'iOS' → 'Unit Testing Bundle' and click Next"
echo ""
echo "4. Configure the test target:"
echo "   - Product Name: rmProAppTests"
echo "   - Team: Select your team"
echo "   - Bundle Identifier: Will be auto-filled"
echo "   - Language: Swift"
echo "   - Target to be Tested: rmProApp"
echo "   - Click Finish"
echo ""
echo "5. When Xcode asks to create a scheme, click 'Activate'"
echo ""
echo "6. Delete the auto-generated test file that Xcode creates"
echo "   (keep the one we already created)"
echo ""
echo "================================"
echo "How to Run Tests"
echo "================================"
echo ""
echo "Once setup is complete, you can run tests with:"
echo ""
echo "From Terminal:"
echo "  xcodebuild test -scheme rmProApp -destination 'platform=iOS Simulator,name=iPhone 15'"
echo ""
echo "From Xcode:"
echo "  Press Cmd+U or Product → Test"
echo ""
echo "To run specific tests:"
echo "  xcodebuild test -scheme rmProApp -only-testing:rmProAppTests/rmProAppTests/testExample"
echo ""