//
//  SampleData.swift
//  rmProApp
//
//  Created by William Castellano on 4/16/25.
//

import Foundation

let sampleRMTenant = RMTenant(
    accountGroupID: 101,
    balance: Decimal(1500.75),
    charges: nil, // Can be populated with RMCharge array if needed
    chargeTypes: nil, // Can be populated with RMChargeType array if needed
    checkPayeeName: "John Doe",
    colorID: 1,
    comment: "Reliable tenant, pays on time.",
    contacts: [
        RMContact(
            contactID: 201,
            firstName: "John",
            lastName: "Doe",
            middleName: "A",
            isActive: true,
            isPrimary: true,
            contactTypeID: 1,
            dateOfBirth: "1985-06-15",
            federalTaxID: "123-45-6789",
            comment: "Primary contact",
            email: "john.doe@example.com",
            license: "D1234567",
            vehicle: "Toyota Camry 2020",
            imageID: nil,
            isShowOnBill: true,
            employer: "Tech Corp",
            applicantType: "Individual",
            createDate: "2023-01-10T10:00:00Z",
            createUserID: 301,
            updateDate: "2024-06-20T12:00:00Z",
            annualIncome: 75000.0,
            updateUserID: 302,
            parentID: 101,
            parentType: "Tenant"
        )
    ],
    createDate: "2023-01-10T10:00:00Z",
    createUserID: 301,
    defaultTaxTypeID: 1,
    doNotAcceptChecks: false,
    doNotAcceptPayments: false,
    doNotAllowTWAPayments: false,
    doNotChargeLateFees: false,
    doNotPrintStatements: false,
    doNotSendARAutomationNotifications: false,
    evictionID: nil,
    failedCalls: 0,
    firstContact: "John Doe",
    firstName: "John",
    flexibleRentInternalStatus: "Approved",
    flexibleRentStatus: "Active",
    isAccountGroupMaster: true,
    isCompany: false,
    isProspect: false,
    isShowCommentBanner: true,
    lastContact: "John Doe",
    lastName: "Doe",
    lastNameFirstName: "Doe, John",
    leases: [
        RMLease(
            leaseID: 401,
            tenantID: 101,
            unitID: 501,
            propertyID: 601,
            isCommercial: false,
            moveInDate: "2023-02-01",
            moveOutDate: nil,
            expectedMoveOutDate: "2025-01-31",
            noticeDate: nil,
            isMoveOutConfirmed: false,
            arrivalDate: "2023-02-01",
            departureDate: nil,
            sortOrder: 1,
            createDate: "2023-01-15T10:00:00Z",
            updateDate: "2023-01-15T10:00:00Z",
            startDate: "2023-02-01",
            endDate: "2025-01-31",
            createUserID: 301,
            updateUserID: 301,
            tenant: nil, // Avoid circular reference; can be set if needed
            unit: RMUnit(
                unitID: 501,
                propertyID: 601,
                name: "Unit 101",
                unitTypeID: 701,
                colorID: 1,
                isVacant: false,
                comment: "Modern apartment",
                addresses: [
                    RMAddress(
                        addressID: 801,
                        addressTypeID: 1,
                        address: "123 Main St, Apt 101",
                        street: "123 Main St",
                        city: "Springfield",
                        state: "IL",
                        postalCode: "62701",
                        isPrimary: true,
                        isBilling: true,
                        parentID: 501,
                        parentType: "Unit",
                        addressType: RMAddressType(
                            addressTypeID: 1,
                            name: "Residential",
                            description: "Primary residential address",
                            sortOrder: 1,
                            parentType: "Unit"
                        )
                    )
                ],
                leases: nil, // Avoid circular reference
                userDefinedValues: nil,
                currentOccupancyStatus: nil,
                currentOccupants: nil,
                primaryAddress: nil,
                unitType: RMUnitType(
                    unitTypeID: 701,
                    name: "2 Bedroom",
                    comment: "Standard 2-bedroom unit",
                    bedrooms: 2,
                    bathrooms: 1,
                    inspectionTemplateID: nil,
                    isExcludeFromRentersInsurance: false,
                    createDate: "2022-12-01T10:00:00Z",
                    createUserID: 301,
                    updateDate: "2022-12-01T10:00:00Z",
                    updateUserID: 301,
                    isOtherRentableItem: false,
                    recurringCharges: nil,
                    units: nil
                )
            ),
            property: RMProperty(
                propertyID: 601,
                name: "Springfield Apartments",
                shortName: "Springfield Apts",
                billingName1: "Springfield Management",
                billingName2: nil,
                managerName: "Jane Smith",
                isActive: true,
                propertyType: "Residential",
                email: "management@springfieldapts.com",
                taxID: "98-7654321",
                comment: "Well-maintained property",
                createDate: "2022-10-01T10:00:00Z",
                updateDate: "2022-10-01T10:00:00Z",
                createUserID: 301,
                updateUserID: 301,
                concurrencyID: 1,
                colorID: 1,
                isLateChargeEnabled: true,
                isEpayEnabled: true,
                defaultBankID: 901,
                postingDay: 1,
                lastMonthlyPost: "2024-04-01",
                lastDailyPost: "2024-04-15",
                evictionWorkflowID: nil,
                unitCount: 50,
                occupiedUnitCount: 48,
                vacantUnitCount: 2,
                lastUnitCountPost: "2024-04-01",
                vacantUnitIDs: "502,503"
            ),
            propertyUnit: "Springfield Apartments - Unit 101",
            unitProperty: "Unit 101 - Springfield Apartments"
        )
    ],
    name: "John Doe",
    openBalance: Decimal(1500.75),
    overrideCreateDate: nil,
    overrideCreateUserID: nil,
    overrideReason: nil,
    overrideScreeningDecision: false,
    overrideUpdateDate: nil,
    overrideUpdateUserID: nil,
    payments: nil, // Can be populated with RMPayment array if needed
    paymentReversals: nil, // Can be populated with RMPaymentReversal array if needed
    postingStartDate: "2023-02-01",
    propertyID: 601,
    recurringChargeSummaries: [
        RMRecurringChargeSummary(
            isException: false,
            groupName: "Rent",
            entityTypeEnumSortOrder: 1,
            tenantID: 101,
            unitTypeID: 701,
            propertyID: 601,
            isInherited: false,
            recurringChargeID: 1001,
            entityType: "Tenant",
            entityKeyID: 101,
            unitID: 501,
            frequency: 1, // Monthly
            chargeTypeID: 1101,
            amount: 1200.0,
            originalAmount: 1200.0,
            amountPerSquareFoot: nil,
            comment: "Monthly rent",
            fromDate: "2023-02-01",
            toDate: nil,
            isCalculated: false,
            calculation: nil,
            camRecurringChargeID: nil,
            sortOrder: 1,
            createDate: "2023-01-15T10:00:00Z",
            createUserID: 301,
            updateDate: "2023-01-15T10:00:00Z",
            updateUserID: 301,
            chargeType: nil // Can be populated with RMChargeType if needed
        )
    ],
    rentDueDay: 1,
    rentPeriod: "Monthly",
    screeningStatus: "Approved",
    securityDepositHeld: 1200,
    securityDepositSummaries: nil, // Can be populated with RMSecurityDepositSummary array if needed
    statementMethod: "Email",
    status: "Active",
    tenantDisplayID: 101,
    tenantID: 101,
    totalCalls: 5,
    totalEmails: 10,
    totalVisits: 2,
    udfs: nil, // Can be populated with RMUserDefinedValue array if needed
    unit: RMUnit(
        unitID: 501,
        propertyID: 601,
        name: "Unit 101",
        unitTypeID: 701,
        colorID: 1,
        isVacant: false,
        comment: "Modern apartment",
        addresses: [
            RMAddress(
                addressID: 801,
                addressTypeID: 1,
                address: "123 Main St, Apt 101",
                street: "123 Main St",
                city: "Springfield",
                state: "IL",
                postalCode: "62701",
                isPrimary: true,
                isBilling: true,
                parentID: 501,
                parentType: "Unit",
                addressType: RMAddressType(
                    addressTypeID: 1,
                    name: "Residential",
                    description: "Primary residential address",
                    sortOrder: 1,
                    parentType: "Unit"
                )
            )
        ],
        leases: nil, // Avoid circular reference
        userDefinedValues: nil,
        currentOccupancyStatus: nil,
        currentOccupants: nil,
        primaryAddress: nil,
        unitType: RMUnitType(
            unitTypeID: 701,
            name: "2 Bedroom",
            comment: "Standard 2-bedroom unit",
            bedrooms: 2,
            bathrooms: 1,
            inspectionTemplateID: nil,
            isExcludeFromRentersInsurance: false,
            createDate: "2022-12-01T10:00:00Z",
            createUserID: 301,
            updateDate: "2022-12-01T10:00:00Z",
            updateUserID: 301,
            isOtherRentableItem: false,
            recurringCharges: nil,
            units: nil
        )
    ),
    updateDate: "2024-06-20T12:00:00Z",
    updateUserID: 302,
    webMessage: "Welcome to Springfield Apartments!",
    addresses: [
        RMAddress(
            addressID: 801,
            addressTypeID: 1,
            address: "123 Main St, Apt 101",
            street: "123 Main St",
            city: "Springfield",
            state: "IL",
            postalCode: "62701",
            isPrimary: true,
            isBilling: true,
            parentID: 101,
            parentType: "Tenant",
            addressType: RMAddressType(
                addressTypeID: 1,
                name: "Residential",
                description: "Primary residential address",
                sortOrder: 1,
                parentType: "Tenant"
            )
        )
    ],
    primaryContact: RMContact(
        contactID: 201,
        firstName: "John",
        lastName: "Doe",
        middleName: "A",
        isActive: true,
        isPrimary: true,
        contactTypeID: 1,
        dateOfBirth: "1985-06-15",
        federalTaxID: "123-45-6789",
        comment: "Primary contact",
        email: "john.doe@example.com",
        license: "D1234567",
        vehicle: "Toyota Camry 2020",
        imageID: nil,
        isShowOnBill: true,
        employer: "Tech Corp",
        applicantType: "Individual",
        createDate: "2023-01-10T10:00:00Z",
        createUserID: 301,
        updateDate: "2024-06-20T12:00:00Z",
        annualIncome: 75000.0,
        updateUserID: 302,
        parentID: 101,
        parentType: "Tenant"
    )
)
